2024-08-08 23:18:13.240632-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "1" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:78)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:18:34.707528-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:78)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:20:55.573255-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:78)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:22:09.815272-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:48:28.348469-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "1" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:48:59.651127-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "6" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:49:52.929075-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:55:25.868909-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "1" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:56:57.053847-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.findColumn(JdbcResultSet.java:178)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:57:23.267342-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "codigo" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.findColumn(JdbcResultSet.java:178)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:57:41.025090-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "CODIGO" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.findColumn(JdbcResultSet.java:178)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:59:18.009145-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "codigo" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:59:38.180928-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "CODIGO" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-08 23:59:58.507411-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "1" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-09 00:00:09.797996-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-09 00:00:21.245961-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "3" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:79)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-09 00:06:56.435061-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:43)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:10)
	at servicio.MedicamentoService.createRecordService(MedicamentoService.java:17)
	at Main.main(Main.java:19)
2024-08-09 00:07:20.303589-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "NOMBRE" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:43)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:10)
	at servicio.MedicamentoService.createRecordService(MedicamentoService.java:17)
	at Main.main(Main.java:19)
2024-08-09 00:11:57.732497-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "SOMBRE" not found [42122-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:43)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:10)
	at servicio.MedicamentoService.createRecordService(MedicamentoService.java:17)
	at Main.main(Main.java:19)
2024-08-09 00:12:36.954530-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:43)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:10)
	at servicio.MedicamentoService.createRecordService(MedicamentoService.java:17)
	at Main.main(Main.java:19)
2024-08-09 00:16:24.105106-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-230]
2024-08-09 00:16:57.761247-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:38)
	at dao.implementacion.LogicaCRUD.guardarRegistro(LogicaCRUD.java:10)
	at servicio.MedicamentoService.createRecordService(MedicamentoService.java:17)
	at Main.main(Main.java:19)
2024-08-09 00:23:50.883763-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Invalid value "3" for parameter "columnIndex" [90008-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:78)
	at dao.implementacion.LogicaCRUD.buscarPorId(LogicaCRUD.java:10)
	at servicio.MedicamentoService.buscarId(MedicamentoService.java:21)
	at Main.main(Main.java:22)
2024-08-09 02:13:55.123317-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP [*]IF EXISTS pacientes; CREATE TABLE pacientes (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DOMICILIO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA_ALTA DATE NOT NULL)"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, MATERIALIZED, VIEW, ROLE, ALIAS, SCHEMA, ALL OBJECTS, DOMAIN, TYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP IF EXISTS pacientes; CREATE TABLE pacientes (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DOMICILIO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA_ALTA DATE NOT NULL) [42001-230]
2024-08-09 02:13:55.667044-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42102-230]
2024-08-09 02:13:55.829150-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTE" not found; SQL statement:
UPDATE paciente SET NOMBRE=?, APELLIDO=?, DOMICILIO=?, DNI=?, FECHA_ALTA=? WHERE ID=? [42102-230]
2024-08-09 02:13:55.947413-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42102-230]
2024-08-09 02:13:56.332615-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42102-230]
2024-08-09 02:13:56.841953-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
SELECT * FROM PACIENTES [42102-230]
2024-08-09 02:15:05.365145-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "DROP [*]IF EXISTS pacientes; CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DOMICILIO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA_ALTA DATE NOT NULL)"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, MATERIALIZED, VIEW, ROLE, ALIAS, SCHEMA, ALL OBJECTS, DOMAIN, TYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP IF EXISTS pacientes; CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DOMICILIO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA_ALTA DATE NOT NULL) [42001-230]
2024-08-09 02:15:05.778921-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42102-230]
2024-08-09 02:15:06.196309-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTE" not found; SQL statement:
UPDATE paciente SET NOMBRE=?, APELLIDO=?, DOMICILIO=?, DNI=?, FECHA_ALTA=? WHERE ID=? [42102-230]
2024-08-09 02:15:06.494360-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42102-230]
2024-08-09 02:15:06.784427-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42102-230]
2024-08-09 02:15:07.095408-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTES" not found; SQL statement:
SELECT * FROM PACIENTES [42102-230]
2024-08-09 02:15:56.687948-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) [*]VALUES(?,?,?,?,?)"; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42000-230]
2024-08-09 02:15:56.872580-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTE" not found; SQL statement:
UPDATE paciente SET NOMBRE=?, APELLIDO=?, DOMICILIO=?, DNI=?, FECHA_ALTA=? WHERE ID=? [42102-230]
2024-08-09 02:15:56.976363-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) [*]VALUES(?,?,?,?,?)"; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42000-230]
2024-08-09 02:15:57.387932-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) [*]VALUES(?,?,?,?,?)"; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42000-230]
2024-08-09 02:16:00.145624-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) [*]VALUES(?,?,?,?,?)"; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42000-230]
2024-08-09 02:16:00.534063-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTE" not found; SQL statement:
UPDATE paciente SET NOMBRE=?, APELLIDO=?, DOMICILIO=?, DNI=?, FECHA_ALTA=? WHERE ID=? [42102-230]
2024-08-09 02:16:01.009019-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) [*]VALUES(?,?,?,?,?)"; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42000-230]
2024-08-09 02:16:01.312790-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) [*]VALUES(?,?,?,?,?)"; SQL statement:
INSERT INTO pacientes VALUES(NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES(?,?,?,?,?) [42000-230]
2024-08-09 02:17:44.012941-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PACIENTE" not found; SQL statement:
UPDATE paciente SET NOMBRE=?, APELLIDO=?, DOMICILIO=?, DNI=?, FECHA_ALTA=? WHERE ID=? [42102-230]
